---
- name: test template print
  hosts: localhost
  connection: local
  vars:
    new_account_id: huehue_from_var
  tasks:

    - name: "print template"
      debug: msg="{{ lookup('template','templates/custom_policy_20170209_v1_engineer.json.j2')  }}"
      
      
      
    - name: Execute  bash script
      shell: chmod +x go.sh && ./go.sh 
      register: out
    
    - name: print message from script
      debug: msg=out
