---
- name: test template print
  hosts: localhost
  connection: local
  vars:
    new_account_id: huehue_from_var
  tasks:

    - name: "print template"
      debug: msg="{{ lookup('template','templates/custom_policy_20170209_v1_engineer.json.j2')  }}"
      
      
    - name: Changing perm of bash file, adding "+x"
      file: dest=go.sh mode=a+x
      
      
    - name: Execute  bash script
      shell: ./go.sh 
      register: out
    
    - name: print message from script
      debug: msg={{ out.stdout }} 
