---
- name: test template print
  hosts: localhost
  connection: local
  vars:
    new_account_id: huehue_from_var
    bash_script_name: go.sh
  tasks:

    - name: "print template"
      debug: msg="{{ lookup('template','templates/custom_policy_20170209_v1_engineer.json.j2')  }}"
      
      
    - name: Changing perm of bash file, adding "+x"
      file: dest="{{ bash_script_name }}" mode=a+x
      
      
    - name: Execute  bash script
      shell: ./"{{ bash_script_name }}" --var xXx --var2 "{{ new_account_id }}"
      register: out
    
    - name: print message from script
      debug: msg={{ out.stdout }} 

    - set_stats:
        data:
          ext_var: out
        per_host: no
      when: ext_var.stdout.find ("FAILED") == -1
